version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chart.js
    versions:
    - 2.9.4
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: "@types/prismjs"
    versions:
    - 1.16.2
    - 1.16.3
    - 1.16.4
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
    - 3.7.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
